# Generated by Django 2.2.4 on 2019-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eid', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('salery', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
